### ISSUE TITLE
It's unclear whether this is satire or actually serious.

### ISSUE THREAD

**Issue by mpldr** [barklan/gotemplate#2]
Due to:
- > Obnoxious amount of pre-commit hooks.
- > run.sh - convenient alternative to Makefile
- Completely redundant packages (`pkg` without any use,  `pkg/myapp` instead of an `internal`)
- "default" Logger using 3rd party dependency
- and more

These almost scream [Enterprise FizzBuzz](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition), but the explicit "you should not do this" is missing which in my eyes makes it almost dangerous to beginners as it promotes the use of non-standard tools, unexplained use of external dependencies, empty packages, and other things generally not considered best practice.

**Comment by mpldr** [comment]
This is by no means meant as an attack (if this project is actually a serious template), but I find it is promoting ideas that can be considered outright dangerous (see also: padleft npm).

**Comment by barklan** [comment]
Yes, I think I should have been more clear with this. This is not a satire and is not meant to be used as is (especially with that ridiculous amount of pre-commit hooks), but rather removing or replacing stuff that is not needed (same for unneeded dependancies). bash functions instead of Makefile were more convenient for me in very specific cases (GitLab CI jobs in containers without gnu make). I was wrong not to explain that.

This has worked for me to quickly bootstrap small services and I do not recommend this as a good for everything (even not best practice) template. Will update repo later. Thanks for your feedback!
